### PR TITLE
Remove support for Ruby 1.9.3

### PR DESCRIPTION
**Pull request by ethirajsrinivasan**

### CODE REVIEW

**Comment by bragboy** [comment]
Can you also update readme with the support ?

**Comment by ethirajsrinivasan** [comment]
Hi Braga

Sorry.Missed this mail between work. Should i update the readme stating
1.9.3 is removed ?

**Comment by bragboy** [comment]
No, not that, just update the `README.md` stating what kind of Rubies we support.

**Comment by ethirajsrinivasan** [comment]
Sure braga

**Pull request merged**
